### PR TITLE
Selectively import/reexport functions

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by pat-s** [comment]
Should mlr3fselect also be added?

**Comment by mllg** [comment]
> Should mlr3fselect also be added?

Yes. mlr3proba and mlr3cluster are also candidates.

**Comment by pat-s** [comment]
@mllg LGTM?

**Comment by pat-s** [comment]
ping @mllg

**Comment by mllg** [comment]
On agenda for next core call.

**Comment by pat-s** [comment]
@mllg any news?

**Pull request merged**
